// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingsController from "./bookings_controller"
application.register("bookings", BookingsController)

import ConcertsController from "./concerts_controller"
application.register("concerts", ConcertsController)

import GroupsController from "./groups_controller"
application.register("groups", GroupsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RangeController from "./range_controller"
application.register("range", RangeController)
